name: babe_resto
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  android_alarm_manager: ^2.0.0
  animated_text_kit: ^4.2.1
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^6.0.0
  flutter_rating_bar: ^4.0.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  lottie: ^1.1.0
  
  path: ^1.8.0
  provider: ^5.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.7
  sqflite: ^2.0.0+3
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/polar-cook.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FCCC74"
  image: assets/images/polar-cook.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotie_animation/
